### ISSUE TITLE
Build failure with GHC 9.4 (please make a metadata revision)

### ISSUE THREAD

**Issue by chris-martin** [jwiegley/async-pool#30]
This package fails to build with GHC 9.4.

```
Building library for async-pool-0.9.1..
[1 of 3] Compiling Control.Concurrent.Async.Pool.Async ( Control/Concurrent/Async/Pool/Async.hs, dist/build/Control/Concurrent/Async/Pool/Async.o, dist/build/Control/Concurrent/Async/Pool/Async.dyn_o )

Control/Concurrent/Async/Pool/Async.hs:714:16: error:
    • Couldn't match expected type: State# RealWorld
                                    -> (# State# RealWorld, a1 #)
                  with actual type: IO ()
    • In the first argument of ‘fork#’, namely ‘action’
      In the expression: fork# action s
      In the expression:
        case (fork# action s) of (# s1, tid #) -> (# s1, ThreadId tid #)
    |
714 |    case (fork# action s) of (# s1, tid #) -> (# s1, ThreadId tid #)
    |                ^^^^^^

Control/Concurrent/Async/Pool/Async.hs:719:22: error:
    • Couldn't match expected type: State# RealWorld
                                    -> (# State# RealWorld, a0 #)
                  with actual type: IO ()
    • In the second argument of ‘forkOn#’, namely ‘action’
      In the expression: forkOn# cpu action s
      In the expression:
        case (forkOn# cpu action s) of
          (# s1, tid #) -> (# s1, ThreadId tid #)
    |
719 |    case (forkOn# cpu action s) of (# s1, tid #) -> (# s1, ThreadId tid #)
    |                      ^^^^^^
```

Please make a metadata revision on `async-pool-9.0.1` to correct the upper bound on `base` from `< 5` to `< 4.17`.

**Comment by TristanCacqueray** [comment]
Dear @jwiegley, could you please make a new release with HEAD to fix compatibility with ghc > 9.4. Thank you in advance.

**Comment by jwiegley** [comment]
@TristanCacqueray I have released it to Hackage as 0.9.2. Please confirm.

**Comment by TristanCacqueray** [comment]
@jwiegley Thank you. I confirm the last release works, here is the nix override I used:

```nix
           async-pool = pkgs.haskell.lib.overrideCabal hpPrev.async-pool {
              version = "0.9.2";
              sha256 = "sha256-cu0zgAN+bJLkL6hOyC6BTcsVaqLEPkHeuQlxUJC0FoM=";
              revision = null;
              editedCabalFile = null;
            };
```

**Comment by vst** [comment]
I think that this can be closed now. Right?

PS: nixpkgs (v23.11) comes with [async-pool v0.9.2](https://search.nixos.org/packages?channel=23.11&from=0&size=50&sort=relevance&type=packages&query=async-pool), the default GHC is v9.4.8 and it compiles well.

**Comment by jwiegley** [comment]
With that report I'll close it, thanks @vst!
